export const WEBSOCKET_EVENTS = {
  HELLO: 'HELLO',
  HELLO_BACK: 'HELLO_BACK',
  ERR_INVALID_DATA: 'ERR_INVALID_DATA',
  TX_NEW: 'TX_NEW',
  TX_CONFIRMED: 'TX_CONFIRMED',
  TX_PENDING: 'TX_PENDING',
  TX_REJECTED: 'TX_REJECTED',
  UTXO_UPDATE: 'UTXO_UPDATE',
  UTXO_QUERY: 'UTXO_QUERY',
  PRISMA_NEW_TX: 'PRISMA_NEW_TX',
};
